# Generated by Django 6.0.3 on 2026-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254)),
                ('message', models.TextField(blank=True, max_length=360)),
                ('color', models.CharField(choices=[('inquiry', 'Inquiry'), ('support', 'Support Request'), ('freelance', 'Freelance Job Opportunities'), ('connect', 'Request to connect/meet'), ('default', '---------------- Select a topic ---------------')], default='default', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
