# Generated by Django 6.0.3 on 2026-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='color',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('support', 'Support Request'), ('freelance', 'Freelance Job Opportunities'), ('connect', 'Request to connect/meet'), ('default', '---------------- Select a subject ---------------')], default='default', max_length=50),
        ),
    ]
