# Generated by Django 6.0.3 on 2026-04-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactus_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='color',
            new_name='subject',
        ),
    ]
