# Generated by Django 6.0.3 on 2026-04-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('default', '----------------&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Select a subject &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ---------------------------------'), ('inquiry', 'Inquiry'), ('support', 'Support Request'), ('freelance', 'Freelance Job Opportunities'), ('connect', 'Request to connect/meet')], default='default', max_length=50),
        ),
    ]
