# Generated by Django 6.0.3 on 2026-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('default', '------------------ Select a subject  ---------------------------------'), ('inquiry', 'Inquiry'), ('support', 'Support Request'), ('freelance', 'Freelance Job Opportunities'), ('connect', 'Request to connect/meet')], default='default', max_length=50),
        ),
    ]
