# Generated by Django 6.0.3 on 2026-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
