# Generated by Django 6.0.3 on 2026-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_sales_order_date_alter_sales_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('initial_stock', models.PositiveIntegerField()),
                ('stock_in', models.PositiveIntegerField()),
                ('stock_sold', models.PositiveIntegerField()),
                ('available_stock', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
