# Generated by Django 6.0.3 on 2026-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_code',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
