# Generated by Django 6.0.3 on 2026-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_product_id_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
