# Generated by Django 6.0.3 on 2026-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_sales_amount_alter_sales_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(unique=True)),
                ('order_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=50)),
                ('ship_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
