# Generated by Django 6.0.3 on 2026-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_samplesales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesales',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
